spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

server:
  port: 8092



management:
  endpoint:
    health:
      enabled: true
